/* =====================================================================
   Support Audit System — full database provisioning script
   Target: SQL Server (CSMSVR02), database RittalSupportSW

   SAFE TO RUN ON AN EXISTING DATABASE. Every step is idempotent: it only
   creates what is missing, and the Dispatch seed updates rows in place if
   they are already there. Run it in SSMS (or sqlcmd) to bring a database
   up to date, or to build one from nothing. Re-running changes nothing.

   It covers:
     1. the RittalSupportSW database (if missing),
     2. the db_Public_User login/user the app connects as,
     3. the full schema (tables, keys, indexes),
     4. the Stores + Dispatch seed data — Stores' four verbatim SHEF014
        task lists, and Dispatch's Warehouse Audit: 24 checks across
        H&S/Quality/Performance/Morale, each carrying its own category,
        cadence, accountable role and escalation window as structured
        columns, seeded across Dispatch's four shifts, plus the HOD roster
        (same five names as the Production Audit System) used for sign-off,
     5. the EF migration-history rows, so the app's startup migration sees
        everything as already applied and makes no further changes.

   SSMS:    open this file, make sure no database is selected in the
            dropdown (the script does its own USE), and Execute.
   sqlcmd:  sqlcmd -S csmsvr02 -E -i create-database.sql

   (Change the login password below before running in production.)
   ===================================================================== */

IF DB_ID(N'RittalSupportSW') IS NULL
BEGIN
    CREATE DATABASE [RittalSupportSW];
END;
GO

USE [RittalSupportSW];
GO

/* ---- Application SQL login / user -----------------------------------
   Matches ConnectionStrings:Default in appsettings.json. Rotate this
   password in production and keep the connection string in step.
   Uses db_owner so the app can also apply future EF migrations on start. */
IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'db_Public_User')
BEGIN
    CREATE LOGIN [db_Public_User] WITH PASSWORD = N'Rittal1234',
        CHECK_POLICY = OFF, DEFAULT_DATABASE = [RittalSupportSW];
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'db_Public_User')
BEGIN
    CREATE USER [db_Public_User] FOR LOGIN [db_Public_User];
    ALTER ROLE [db_owner] ADD MEMBER [db_Public_User];
END;
GO

/* ---- Schema + seed data + migration history -------------------------
   (generated by: dotnet ef migrations script --idempotent) */

IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [Departments] (
        [Id] int NOT NULL IDENTITY,
        [Name] nvarchar(200) NOT NULL,
        [SortOrder] int NOT NULL,
        [IsActive] bit NOT NULL,
        CONSTRAINT [PK_Departments] PRIMARY KEY ([Id])
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [Areas] (
        [Id] int NOT NULL IDENTITY,
        [DepartmentId] int NOT NULL,
        [Name] nvarchar(200) NOT NULL,
        [DefaultLocation] nvarchar(max) NULL,
        [SortOrder] int NOT NULL,
        [IsActive] bit NOT NULL,
        CONSTRAINT [PK_Areas] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_Areas_Departments_DepartmentId] FOREIGN KEY ([DepartmentId]) REFERENCES [Departments] ([Id]) ON DELETE CASCADE
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [Shifts] (
        [Id] int NOT NULL IDENTITY,
        [DepartmentId] int NOT NULL,
        [Name] nvarchar(200) NOT NULL,
        [SortOrder] int NOT NULL,
        [IsActive] bit NOT NULL,
        CONSTRAINT [PK_Shifts] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_Shifts_Departments_DepartmentId] FOREIGN KEY ([DepartmentId]) REFERENCES [Departments] ([Id]) ON DELETE CASCADE
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [TaskLists] (
        [Id] int NOT NULL IDENTITY,
        [AreaId] int NOT NULL,
        [ShiftId] int NOT NULL,
        [Version] int NOT NULL,
        [IsCurrent] bit NOT NULL,
        [HealthRepsReminder] nvarchar(max) NULL,
        [CreatedAt] datetime2 NOT NULL,
        [CreatedBy] nvarchar(256) NULL,
        CONSTRAINT [PK_TaskLists] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_TaskLists_Areas_AreaId] FOREIGN KEY ([AreaId]) REFERENCES [Areas] ([Id]) ON DELETE CASCADE,
        CONSTRAINT [FK_TaskLists_Shifts_ShiftId] FOREIGN KEY ([ShiftId]) REFERENCES [Shifts] ([Id]) ON DELETE NO ACTION
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [ChecklistSubmissions] (
        [Id] int NOT NULL IDENTITY,
        [AreaId] int NOT NULL,
        [ShiftId] int NOT NULL,
        [TaskListId] int NOT NULL,
        [ChecklistDate] date NOT NULL,
        [AuditorNames] nvarchar(max) NULL,
        [Location] nvarchar(max) NULL,
        [CreatedAt] datetime2 NOT NULL,
        [CreatedBy] nvarchar(256) NULL,
        [LastEditedAt] datetime2 NULL,
        [LastEditedBy] nvarchar(256) NULL,
        [CompletedAt] datetime2 NULL,
        [CompletedBy] nvarchar(256) NULL,
        CONSTRAINT [PK_ChecklistSubmissions] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_ChecklistSubmissions_Areas_AreaId] FOREIGN KEY ([AreaId]) REFERENCES [Areas] ([Id]) ON DELETE NO ACTION,
        CONSTRAINT [FK_ChecklistSubmissions_Shifts_ShiftId] FOREIGN KEY ([ShiftId]) REFERENCES [Shifts] ([Id]) ON DELETE NO ACTION,
        CONSTRAINT [FK_ChecklistSubmissions_TaskLists_TaskListId] FOREIGN KEY ([TaskListId]) REFERENCES [TaskLists] ([Id]) ON DELETE NO ACTION
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [TaskItems] (
        [Id] int NOT NULL IDENTITY,
        [TaskListId] int NOT NULL,
        [Text] nvarchar(max) NOT NULL,
        [SortOrder] int NOT NULL,
        [IsTimeBoxed] bit NOT NULL,
        CONSTRAINT [PK_TaskItems] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_TaskItems_TaskLists_TaskListId] FOREIGN KEY ([TaskListId]) REFERENCES [TaskLists] ([Id]) ON DELETE CASCADE
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [TaskCheckpoints] (
        [Id] int NOT NULL IDENTITY,
        [TaskItemId] int NOT NULL,
        [Label] nvarchar(120) NOT NULL,
        [SortOrder] int NOT NULL,
        CONSTRAINT [PK_TaskCheckpoints] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_TaskCheckpoints_TaskItems_TaskItemId] FOREIGN KEY ([TaskItemId]) REFERENCES [TaskItems] ([Id]) ON DELETE CASCADE
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [TaskResponses] (
        [Id] int NOT NULL IDENTITY,
        [ChecklistSubmissionId] int NOT NULL,
        [TaskItemId] int NOT NULL,
        [Status] nvarchar(20) NULL,
        [Notes] nvarchar(max) NULL,
        [UpdatedAt] datetime2 NULL,
        CONSTRAINT [PK_TaskResponses] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_TaskResponses_ChecklistSubmissions_ChecklistSubmissionId] FOREIGN KEY ([ChecklistSubmissionId]) REFERENCES [ChecklistSubmissions] ([Id]) ON DELETE CASCADE,
        CONSTRAINT [FK_TaskResponses_TaskItems_TaskItemId] FOREIGN KEY ([TaskItemId]) REFERENCES [TaskItems] ([Id]) ON DELETE NO ACTION
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [CheckpointResponses] (
        [Id] int NOT NULL IDENTITY,
        [TaskResponseId] int NOT NULL,
        [TaskCheckpointId] int NOT NULL,
        [Ticked] bit NOT NULL,
        [TickedAt] datetime2 NULL,
        CONSTRAINT [PK_CheckpointResponses] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_CheckpointResponses_TaskCheckpoints_TaskCheckpointId] FOREIGN KEY ([TaskCheckpointId]) REFERENCES [TaskCheckpoints] ([Id]) ON DELETE NO ACTION,
        CONSTRAINT [FK_CheckpointResponses_TaskResponses_TaskResponseId] FOREIGN KEY ([TaskResponseId]) REFERENCES [TaskResponses] ([Id]) ON DELETE CASCADE
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE UNIQUE INDEX [IX_Areas_DepartmentId_Name] ON [Areas] ([DepartmentId], [Name]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_ChecklistSubmissions_AreaId] ON [ChecklistSubmissions] ([AreaId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_ChecklistSubmissions_ChecklistDate_AreaId_ShiftId] ON [ChecklistSubmissions] ([ChecklistDate], [AreaId], [ShiftId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_ChecklistSubmissions_ShiftId] ON [ChecklistSubmissions] ([ShiftId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_ChecklistSubmissions_TaskListId] ON [ChecklistSubmissions] ([TaskListId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_CheckpointResponses_TaskCheckpointId] ON [CheckpointResponses] ([TaskCheckpointId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_CheckpointResponses_TaskResponseId] ON [CheckpointResponses] ([TaskResponseId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE UNIQUE INDEX [IX_Departments_Name] ON [Departments] ([Name]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE UNIQUE INDEX [IX_Shifts_DepartmentId_Name] ON [Shifts] ([DepartmentId], [Name]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_TaskCheckpoints_TaskItemId] ON [TaskCheckpoints] ([TaskItemId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_TaskItems_TaskListId] ON [TaskItems] ([TaskListId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_TaskLists_AreaId_ShiftId_IsCurrent] ON [TaskLists] ([AreaId], [ShiftId], [IsCurrent]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_TaskLists_ShiftId] ON [TaskLists] ([ShiftId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_TaskResponses_ChecklistSubmissionId_TaskItemId] ON [TaskResponses] ([ChecklistSubmissionId], [TaskItemId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_TaskResponses_TaskItemId] ON [TaskResponses] ([TaskItemId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260907093357_InitialCreate', N'8.0.0');
END;
GO

COMMIT;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093744_SeedSupportData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Name', N'SortOrder', N'IsActive') AND [object_id] = OBJECT_ID(N'[Departments]'))
        SET IDENTITY_INSERT [Departments] ON;
    EXEC(N'INSERT INTO [Departments] ([Id], [Name], [SortOrder], [IsActive])
    VALUES (1, N''Stores'', 1, CAST(1 AS bit)),
    (2, N''Dispatch'', 2, CAST(1 AS bit))');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Name', N'SortOrder', N'IsActive') AND [object_id] = OBJECT_ID(N'[Departments]'))
        SET IDENTITY_INSERT [Departments] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093744_SeedSupportData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'DepartmentId', N'Name', N'DefaultLocation', N'SortOrder', N'IsActive') AND [object_id] = OBJECT_ID(N'[Areas]'))
        SET IDENTITY_INSERT [Areas] ON;
    EXEC(N'INSERT INTO [Areas] ([Id], [DepartmentId], [Name], [DefaultLocation], [SortOrder], [IsActive])
    VALUES (1, 1, N''Stores DP1 & DP3'', N''DP1 & DP3'', 1, CAST(1 AS bit)),
    (2, 1, N''Consumables'', N''Consumables'', 2, CAST(1 AS bit))');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'DepartmentId', N'Name', N'DefaultLocation', N'SortOrder', N'IsActive') AND [object_id] = OBJECT_ID(N'[Areas]'))
        SET IDENTITY_INSERT [Areas] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093744_SeedSupportData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'DepartmentId', N'Name', N'SortOrder', N'IsActive') AND [object_id] = OBJECT_ID(N'[Shifts]'))
        SET IDENTITY_INSERT [Shifts] ON;
    EXEC(N'INSERT INTO [Shifts] ([Id], [DepartmentId], [Name], [SortOrder], [IsActive])
    VALUES (1, 1, N''1st'', 1, CAST(1 AS bit)),
    (2, 1, N''2nd'', 2, CAST(1 AS bit)),
    (3, 1, N''3rd'', 3, CAST(1 AS bit)),
    (4, 1, N''Continental nights'', 4, CAST(1 AS bit))');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'DepartmentId', N'Name', N'SortOrder', N'IsActive') AND [object_id] = OBJECT_ID(N'[Shifts]'))
        SET IDENTITY_INSERT [Shifts] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093744_SeedSupportData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'AreaId', N'ShiftId', N'Version', N'IsCurrent', N'HealthRepsReminder', N'CreatedAt', N'CreatedBy') AND [object_id] = OBJECT_ID(N'[TaskLists]'))
        SET IDENTITY_INSERT [TaskLists] ON;
    EXEC(N'INSERT INTO [TaskLists] ([Id], [AreaId], [ShiftId], [Version], [IsCurrent], [HealthRepsReminder], [CreatedAt], [CreatedBy])
    VALUES (1, 1, 1, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed''),
    (2, 1, 2, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed''),
    (3, 1, 3, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed''),
    (4, 1, 4, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed''),
    (5, 2, 1, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed''),
    (6, 2, 2, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed''),
    (7, 2, 3, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed''),
    (8, 2, 4, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'AreaId', N'ShiftId', N'Version', N'IsCurrent', N'HealthRepsReminder', N'CreatedAt', N'CreatedBy') AND [object_id] = OBJECT_ID(N'[TaskLists]'))
        SET IDENTITY_INSERT [TaskLists] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093744_SeedSupportData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'TaskListId', N'Text', N'SortOrder', N'IsTimeBoxed') AND [object_id] = OBJECT_ID(N'[TaskItems]'))
        SET IDENTITY_INSERT [TaskItems] ON;
    EXEC(N'INSERT INTO [TaskItems] ([Id], [TaskListId], [Text], [SortOrder], [IsTimeBoxed])
    VALUES (1, 1, N''Complete pre shift check book been done on the forklift/ ppt and pallet trucks'', 0, CAST(0 AS bit)),
    (2, 1, N''Tidy the yard at both ends and ensure returns ready for collection: pallets / stillages & German returns'', 1, CAST(0 AS bit)),
    (3, 1, N''order everything for today’s production (spc / AMC TRACKING sheet)'', 2, CAST(0 AS bit)),
    (4, 1, N''stock check the gas at dp1 and raise any shortages. correct if needed on sap'', 3, CAST(0 AS bit)),
    (5, 1, N''Check that the gas cage is tidy and all bottles stored safely, action if not'', 4, CAST(0 AS bit)),
    (6, 1, N''Count pallet trailers and raise potential shortages for the next shift - Escalate any issues.'', 5, CAST(0 AS bit)),
    (7, 1, N''send any parcels to consumables to be processed – first batch by 9.30am'', 6, CAST(0 AS bit)),
    (8, 1, N''send any parcels to consumables to be processed – Batch 2 by 11.30am'', 7, CAST(0 AS bit)),
    (9, 1, N''send any parcels to consumables to be processed – batch 3 by 1.30pm'', 8, CAST(0 AS bit)),
    (10, 1, N''Inspect racking areas and report any damage, also remove any unnecessary banding or shrink wrap you find hanging from the racks'', 9, CAST(0 AS bit)),
    (11, 1, N''inspect floors and fire exit and ensure they are clear of obstructions. IE: Pallets, stillages and empty crates'', 10, CAST(1 AS bit)),
    (12, 1, N''Check verticals on order to replace any pallets used'', 11, CAST(1 AS bit)),
    (13, 1, N''Inspect DP1 – move any pallets of steel over hanging the WALKWAYS and ensure coils are not exceeding the blue height restriction line'', 12, CAST(0 AS bit)),
    (14, 1, N''inspect pallets in stores and ensure we have no sharp edge pallets'', 13, CAST(0 AS bit)),
    (15, 1, N''sweep through the store and ensure it is tidy for the next shift.'', 14, CAST(0 AS bit)),
    (16, 2, N''has the pre shift check books been done on the forklift / ppt and the pallets trucks?'', 0, CAST(0 AS bit)),
    (17, 2, N''Have the pallet trailers been counted and any potential shortages been raised for the next shift? Escalate any issues.'', 1, CAST(0 AS bit)),
    (18, 2, N''Have we ordered the tx so it’s on site for 23:00 start'', 2, CAST(0 AS bit)),
    (19, 2, N''Have we located everything that was booked in by the previous shift and cleared option 1 put away?'', 3, CAST(0 AS bit)),
    (20, 2, N''is the mla area clean and tidy with no returned stock just sitting around. If SO, please return to the correct stores'', 4, CAST(0 AS bit)),
    (21, 2, N''Check the racking for anything hanging down and correct this IE: banding, shrink wrap etc.'', 5, CAST(0 AS bit)),
    (22, 2, N''Has the parcel shelf been sent to consumables to be processed? Every 2 hours'', 6, CAST(1 AS bit)),
    (23, 2, N''Are racking areas safe? And all damage if any has been reported'', 7, CAST(0 AS bit)),
    (24, 2, N''Are floors and fire exit clear of obstructions. IE: Pallets, stillages and empty crates'', 8, CAST(0 AS bit)),
    (25, 2, N''have the scrap caps been loaded onto the Ferguson’s trailer'', 9, CAST(0 AS bit)),
    (26, 2, N''Have we cycle counted the pallet trailers and corrected the stocks'', 10, CAST(0 AS bit)),
    (27, 2, N''have the verticals been ordered every time we issue a pallet so we have constant stock flow?'', 11, CAST(0 AS bit)),
    (28, 2, N''Are pallets of steel over hanging the WALKWAYS in dp1 and not exceeding the blue hight restriction line?'', 12, CAST(0 AS bit)),
    (29, 2, N''are the operators ENSURING that we have no sharp edge pallets in the stores'', 13, CAST(0 AS bit)),
    (30, 2, N''have we swept through the store and is it tidy for the next shift.'', 14, CAST(0 AS bit)),
    (31, 3, N''Has the pre shift check book been done on the forklift/ ppt and pallet trucks?'', 0, CAST(0 AS bit)),
    (32, 3, N''Are racking areas safe? And all damage if any has been reported'', 1, CAST(0 AS bit)),
    (33, 3, N''Are all pallets strapped and stored safely at DP1 / DP3'', 2, CAST(0 AS bit)),
    (34, 3, N''Is the TX on the line and not still in stores?'', 3, CAST(0 AS bit)),
    (35, 3, N''Have the parcels been sent to consumables to be processed? Every two hours on this!'', 4, CAST(1 AS bit)),
    (36, 3, N''Are floors and fire exit clear of obstructions. IE: Pallets, stillages and empty crates'', 5, CAST(0 AS bit)),
    (37, 3, N''Do the racks have any banding or shrink wrap hanging from them that needs removing?'', 6, CAST(0 AS bit)),
    (38, 3, N''Are pallets of steel over hanging the WALKWAYS in dp1 and not exceeding the blue hight restriction line?'', 7, CAST(0 AS bit)),
    (39, 3, N''Are the cycle counts done for the day and if not please ensure they are finished.'', 8, CAST(0 AS bit)),
    (40, 3, N''are the operators ENSURING that we have no sharp edge pallets in the stores'', 9, CAST(0 AS bit)),
    (41, 3, N''Is the put away clear for the next shift and all deliveries put away?'', 10, CAST(0 AS bit)),
    (42, 3, N''have we swept through the store and is it tidy for the next shift.'', 11, CAST(0 AS bit));
    INSERT INTO [TaskItems] ([Id], [TaskListId], [Text], [SortOrder], [IsTimeBoxed])
    VALUES (43, 4, N''Has the pre shift check book been done on the forklift/ ppt and pallet trucks?'', 0, CAST(0 AS bit)),
    (44, 4, N''Are racking areas safe? And all damage if any has been reported'', 1, CAST(0 AS bit)),
    (45, 4, N''Are all pallets strapped and stored safely at DP1'', 2, CAST(0 AS bit)),
    (46, 4, N''Is the coils area safe and nothing blocking the fire exit or obstructing the WALKWAYS'', 3, CAST(0 AS bit)),
    (47, 4, N''Do the racks have any banding or shrink wrap hanging from them that needs removing?'', 4, CAST(0 AS bit)),
    (48, 4, N''Are pallets of steel over hanging the WALKWAYS in dp1 and not exceeding the blue hight restriction line?'', 5, CAST(0 AS bit)),
    (49, 4, N''Are the cycle counts done for the day and if not please ensure they are finished.'', 6, CAST(0 AS bit)),
    (50, 4, N''Is the put away clear for the next shift and all deliveries put away?'', 7, CAST(0 AS bit)),
    (51, 4, N''Have the scrap tables and bins been emptied for the next shift and not left so production is stopped at 07:00'', 8, CAST(0 AS bit)),
    (52, 4, N''have we swept through the store and is it tidy for the next shift. If no ask DP3 to support'', 9, CAST(0 AS bit))');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'TaskListId', N'Text', N'SortOrder', N'IsTimeBoxed') AND [object_id] = OBJECT_ID(N'[TaskItems]'))
        SET IDENTITY_INSERT [TaskItems] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093744_SeedSupportData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'TaskItemId', N'Label', N'SortOrder') AND [object_id] = OBJECT_ID(N'[TaskCheckpoints]'))
        SET IDENTITY_INSERT [TaskCheckpoints] ON;
    EXEC(N'INSERT INTO [TaskCheckpoints] ([Id], [TaskItemId], [Label], [SortOrder])
    VALUES (1, 11, N''9am'', 0),
    (2, 11, N''11am'', 1),
    (3, 11, N''1pm'', 2),
    (4, 11, N''3pm'', 3),
    (5, 12, N''9am'', 0),
    (6, 12, N''11am'', 1),
    (7, 12, N''1pm'', 2),
    (8, 12, N''3pm'', 3),
    (9, 22, N''Batch 1'', 0),
    (10, 22, N''Batch 2'', 1),
    (11, 22, N''Batch 3'', 2),
    (12, 22, N''Batch 4'', 3),
    (13, 35, N''Batch 1'', 0),
    (14, 35, N''Batch 2'', 1),
    (15, 35, N''Batch 3'', 2),
    (16, 35, N''Batch 4'', 3)');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'TaskItemId', N'Label', N'SortOrder') AND [object_id] = OBJECT_ID(N'[TaskCheckpoints]'))
        SET IDENTITY_INSERT [TaskCheckpoints] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093744_SeedSupportData'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260907093744_SeedSupportData', N'8.0.0');
END;
GO

COMMIT;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908110000_AddDispatchAccountability'
)
BEGIN
    ALTER TABLE [TaskItems] ADD [Cadence] nvarchar(100) NULL;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908110000_AddDispatchAccountability'
)
BEGIN
    ALTER TABLE [TaskItems] ADD [Category] nvarchar(100) NULL;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908110000_AddDispatchAccountability'
)
BEGIN
    ALTER TABLE [TaskItems] ADD [EscalateToRole] nvarchar(100) NULL;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908110000_AddDispatchAccountability'
)
BEGIN
    ALTER TABLE [TaskItems] ADD [EscalationWindow] nvarchar(100) NULL;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908110000_AddDispatchAccountability'
)
BEGIN
    ALTER TABLE [TaskItems] ADD [ResponsibleRole] nvarchar(100) NULL;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908110000_AddDispatchAccountability'
)
BEGIN
    ALTER TABLE [ChecklistSubmissions] ADD [HodSignOffAt] datetime2 NULL;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908110000_AddDispatchAccountability'
)
BEGIN
    ALTER TABLE [ChecklistSubmissions] ADD [HodSignOffName] nvarchar(256) NULL;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908110000_AddDispatchAccountability'
)
BEGIN
    CREATE TABLE [RosterPeople] (
        [Id] int NOT NULL IDENTITY,
        [ListKind] nvarchar(40) NOT NULL,
        [Name] nvarchar(200) NOT NULL,
        [SortOrder] int NOT NULL,
        [IsActive] bit NOT NULL,
        CONSTRAINT [PK_RosterPeople] PRIMARY KEY ([Id])
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908110000_AddDispatchAccountability'
)
BEGIN
    CREATE UNIQUE INDEX [IX_RosterPeople_ListKind_Name] ON [RosterPeople] ([ListKind], [Name]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908110000_AddDispatchAccountability'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260908110000_AddDispatchAccountability', N'8.0.0');
END;
GO

COMMIT;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908152553_SeedDispatchWarehouseAudit'
)
BEGIN
    SET IDENTITY_INSERT [Areas] ON;
    MERGE [Areas] AS t
    USING (VALUES
        (3, 2, N'Warehouse', N'Warehouse', 1, 1)
    ) AS s([Id], [DepartmentId], [Name], [DefaultLocation], [SortOrder], [IsActive])
    ON t.[Id] = s.[Id]
    WHEN MATCHED THEN UPDATE SET t.[DepartmentId] = s.[DepartmentId], t.[Name] = s.[Name], t.[DefaultLocation] = s.[DefaultLocation], t.[SortOrder] = s.[SortOrder], t.[IsActive] = s.[IsActive]
    WHEN NOT MATCHED THEN INSERT ([Id], [DepartmentId], [Name], [DefaultLocation], [SortOrder], [IsActive])
        VALUES (s.[Id], s.[DepartmentId], s.[Name], s.[DefaultLocation], s.[SortOrder], s.[IsActive]);
    SET IDENTITY_INSERT [Areas] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908152553_SeedDispatchWarehouseAudit'
)
BEGIN
    SET IDENTITY_INSERT [Shifts] ON;
    MERGE [Shifts] AS t
    USING (VALUES
        (5, 2, N'1st', 1, 1),
        (6, 2, N'2nd', 2, 1),
        (7, 2, N'3rd', 3, 1),
        (8, 2, N'Continental nights', 4, 1)
    ) AS s([Id], [DepartmentId], [Name], [SortOrder], [IsActive])
    ON t.[Id] = s.[Id]
    WHEN MATCHED THEN UPDATE SET t.[DepartmentId] = s.[DepartmentId], t.[Name] = s.[Name], t.[SortOrder] = s.[SortOrder], t.[IsActive] = s.[IsActive]
    WHEN NOT MATCHED THEN INSERT ([Id], [DepartmentId], [Name], [SortOrder], [IsActive])
        VALUES (s.[Id], s.[DepartmentId], s.[Name], s.[SortOrder], s.[IsActive]);
    SET IDENTITY_INSERT [Shifts] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908152553_SeedDispatchWarehouseAudit'
)
BEGIN
    SET IDENTITY_INSERT [TaskLists] ON;
    MERGE [TaskLists] AS t
    USING (VALUES
        (9, 3, 5, 1, 1, NULL, '2026-01-01T00:00:00.000', N'System seed'),
        (10, 3, 6, 1, 1, NULL, '2026-01-01T00:00:00.000', N'System seed'),
        (11, 3, 7, 1, 1, NULL, '2026-01-01T00:00:00.000', N'System seed'),
        (12, 3, 8, 1, 1, NULL, '2026-01-01T00:00:00.000', N'System seed')
    ) AS s([Id], [AreaId], [ShiftId], [Version], [IsCurrent], [HealthRepsReminder], [CreatedAt], [CreatedBy])
    ON t.[Id] = s.[Id]
    WHEN MATCHED THEN UPDATE SET t.[AreaId] = s.[AreaId], t.[ShiftId] = s.[ShiftId], t.[Version] = s.[Version], t.[IsCurrent] = s.[IsCurrent], t.[HealthRepsReminder] = s.[HealthRepsReminder], t.[CreatedAt] = s.[CreatedAt], t.[CreatedBy] = s.[CreatedBy]
    WHEN NOT MATCHED THEN INSERT ([Id], [AreaId], [ShiftId], [Version], [IsCurrent], [HealthRepsReminder], [CreatedAt], [CreatedBy])
        VALUES (s.[Id], s.[AreaId], s.[ShiftId], s.[Version], s.[IsCurrent], s.[HealthRepsReminder], s.[CreatedAt], s.[CreatedBy]);
    SET IDENTITY_INSERT [TaskLists] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908152553_SeedDispatchWarehouseAudit'
)
BEGIN
    SET IDENTITY_INSERT [TaskItems] ON;
    MERGE [TaskItems] AS t
    USING (VALUES
        (53, 9, N'Walkways, fire exits and emergency routes are clear', 0, 1, N'H&S', N'Hourly', N'Senior Operator', N'HOD', N'immediately'),
        (54, 9, N'PPE requirements are being followed', 1, 1, N'H&S', N'Hourly', N'Senior Operator', N'HOD', N'immediately'),
        (55, 9, N'No unsafe stacking, damaged pallets or falling-object risks (Mezz Floor)', 2, 1, N'H&S', N'Hourly', N'Senior Operator', NULL, N'immediately'),
        (56, 9, N'Loading bays, dock levellers and vehicle Security is safe (Rite Height)', 3, 1, N'H&S', N'Hourly', N'Senior Operator', N'HOD', N'immediately'),
        (57, 9, N'Correct product, quantity and destination are being picked (Bay Sheets)', 4, 1, N'Quality', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (58, 9, N'Labels, paperwork and scanning are accurate (Check Scanner V Loading)', 5, 1, N'Quality', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (59, 9, N'Picking and despatch activity is on plan', 6, 1, N'Performance', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (60, 9, N'Bottlenecks, downtime and waiting vehicles are controlled', 7, 1, N'Performance', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (61, 9, N'Pre-use equipment checks are completed and defects reported (Check Booklets)', 8, 0, N'H&S', N'Per Shift', N'Senior Operator', N'HOD', N'immediately'),
        (62, 9, N'Spill kits, first-aid and fire points are accessible', 9, 0, N'H&S', N'Per Shift', N'Senior Operator', NULL, N'immediately'),
        (63, 9, N'Pedestrian and MHE segregation controls are effective', 10, 0, N'H&S', N'Per Shift', N'Senior Operator', N'HOD', N'immediately'),
        (64, 9, N'Packaging standards and load security are acceptable', 11, 0, N'Quality', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (65, 9, N'Damaged, quarantined or non-conforming stock is controlled On Hold Products Red Card', 12, 0, N'Quality', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (66, 9, N'FIFO/stock rotation requirements are followed where applicable (New)', 13, 0, N'Quality', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (67, 9, N'Shift plan, priorities and cut-off times were communicated (Shift Start Up)', 14, 0, N'Performance', N'Per Shift', N'HOD', NULL, N'within the same shift'),
        (68, 9, N'Labour and equipment resources are adequate for the plan', 15, 0, N'Performance', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (69, 9, N'Shift KPIs, backlog and carry-over work were reviewed (RPS)', 16, 0, N'Performance', N'Per Shift', N'Senior Operator', N'HOD', N'by the next shift'),
        (70, 9, N'Team brief and safety message were completed ( Start of Each Shift Team Brief)', 17, 0, N'Morale', N'Per Shift', N'HOD', NULL, N'within the same shift'),
        (71, 9, N'Team concerns, support needs and training gaps were discussed', 18, 0, N'Morale', N'Per Shift', N'HOD', NULL, N'by the next shift'),
        (72, 9, N'Good performance and positive behaviours were recognised', 19, 0, N'Morale', N'Per Shift', N'Senior Operator', N'HOD', N'by the next shift'),
        (73, 9, N'General housekeeping and waste controls meet standard', 20, 0, N'H&S', N'Daily', N'Senior Operator', N'HOD', N'within the same day'),
        (74, 9, N'A sample of completed orders was checked for accuracy ( PickList V Shipping Documents)', 21, 0, N'Quality', N'Daily', N'Senior Operator', N'HOD', N'within the same day'),
        (75, 9, N'Daily output, service, productivity and missed deadlines were reviewed ( Transport Late Runners, No Shows)', 22, 0, N'Performance', N'Daily', N'Senior Operator', NULL, N'within the same day'),
        (76, 9, N'Absence, overtime, workload and welfare concerns were reviewed', 23, 0, N'Morale', N'Daily', N'HOD', NULL, N'within the same day'),
        (77, 10, N'Walkways, fire exits and emergency routes are clear', 0, 1, N'H&S', N'Hourly', N'Senior Operator', N'HOD', N'immediately'),
        (78, 10, N'PPE requirements are being followed', 1, 1, N'H&S', N'Hourly', N'Senior Operator', N'HOD', N'immediately'),
        (79, 10, N'No unsafe stacking, damaged pallets or falling-object risks (Mezz Floor)', 2, 1, N'H&S', N'Hourly', N'Senior Operator', NULL, N'immediately'),
        (80, 10, N'Loading bays, dock levellers and vehicle Security is safe (Rite Height)', 3, 1, N'H&S', N'Hourly', N'Senior Operator', N'HOD', N'immediately'),
        (81, 10, N'Correct product, quantity and destination are being picked (Bay Sheets)', 4, 1, N'Quality', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (82, 10, N'Labels, paperwork and scanning are accurate (Check Scanner V Loading)', 5, 1, N'Quality', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (83, 10, N'Picking and despatch activity is on plan', 6, 1, N'Performance', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (84, 10, N'Bottlenecks, downtime and waiting vehicles are controlled', 7, 1, N'Performance', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (85, 10, N'Pre-use equipment checks are completed and defects reported (Check Booklets)', 8, 0, N'H&S', N'Per Shift', N'Senior Operator', N'HOD', N'immediately'),
        (86, 10, N'Spill kits, first-aid and fire points are accessible', 9, 0, N'H&S', N'Per Shift', N'Senior Operator', NULL, N'immediately'),
        (87, 10, N'Pedestrian and MHE segregation controls are effective', 10, 0, N'H&S', N'Per Shift', N'Senior Operator', N'HOD', N'immediately'),
        (88, 10, N'Packaging standards and load security are acceptable', 11, 0, N'Quality', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (89, 10, N'Damaged, quarantined or non-conforming stock is controlled On Hold Products Red Card', 12, 0, N'Quality', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (90, 10, N'FIFO/stock rotation requirements are followed where applicable (New)', 13, 0, N'Quality', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (91, 10, N'Shift plan, priorities and cut-off times were communicated (Shift Start Up)', 14, 0, N'Performance', N'Per Shift', N'HOD', NULL, N'within the same shift'),
        (92, 10, N'Labour and equipment resources are adequate for the plan', 15, 0, N'Performance', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (93, 10, N'Shift KPIs, backlog and carry-over work were reviewed (RPS)', 16, 0, N'Performance', N'Per Shift', N'Senior Operator', N'HOD', N'by the next shift'),
        (94, 10, N'Team brief and safety message were completed ( Start of Each Shift Team Brief)', 17, 0, N'Morale', N'Per Shift', N'HOD', NULL, N'within the same shift'),
        (95, 10, N'Team concerns, support needs and training gaps were discussed', 18, 0, N'Morale', N'Per Shift', N'HOD', NULL, N'by the next shift'),
        (96, 10, N'Good performance and positive behaviours were recognised', 19, 0, N'Morale', N'Per Shift', N'Senior Operator', N'HOD', N'by the next shift'),
        (97, 10, N'General housekeeping and waste controls meet standard', 20, 0, N'H&S', N'Daily', N'Senior Operator', N'HOD', N'within the same day'),
        (98, 10, N'A sample of completed orders was checked for accuracy ( PickList V Shipping Documents)', 21, 0, N'Quality', N'Daily', N'Senior Operator', N'HOD', N'within the same day'),
        (99, 10, N'Daily output, service, productivity and missed deadlines were reviewed ( Transport Late Runners, No Shows)', 22, 0, N'Performance', N'Daily', N'Senior Operator', NULL, N'within the same day'),
        (100, 10, N'Absence, overtime, workload and welfare concerns were reviewed', 23, 0, N'Morale', N'Daily', N'HOD', NULL, N'within the same day'),
        (101, 11, N'Walkways, fire exits and emergency routes are clear', 0, 1, N'H&S', N'Hourly', N'Senior Operator', N'HOD', N'immediately'),
        (102, 11, N'PPE requirements are being followed', 1, 1, N'H&S', N'Hourly', N'Senior Operator', N'HOD', N'immediately'),
        (103, 11, N'No unsafe stacking, damaged pallets or falling-object risks (Mezz Floor)', 2, 1, N'H&S', N'Hourly', N'Senior Operator', NULL, N'immediately'),
        (104, 11, N'Loading bays, dock levellers and vehicle Security is safe (Rite Height)', 3, 1, N'H&S', N'Hourly', N'Senior Operator', N'HOD', N'immediately'),
        (105, 11, N'Correct product, quantity and destination are being picked (Bay Sheets)', 4, 1, N'Quality', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (106, 11, N'Labels, paperwork and scanning are accurate (Check Scanner V Loading)', 5, 1, N'Quality', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (107, 11, N'Picking and despatch activity is on plan', 6, 1, N'Performance', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (108, 11, N'Bottlenecks, downtime and waiting vehicles are controlled', 7, 1, N'Performance', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (109, 11, N'Pre-use equipment checks are completed and defects reported (Check Booklets)', 8, 0, N'H&S', N'Per Shift', N'Senior Operator', N'HOD', N'immediately'),
        (110, 11, N'Spill kits, first-aid and fire points are accessible', 9, 0, N'H&S', N'Per Shift', N'Senior Operator', NULL, N'immediately'),
        (111, 11, N'Pedestrian and MHE segregation controls are effective', 10, 0, N'H&S', N'Per Shift', N'Senior Operator', N'HOD', N'immediately'),
        (112, 11, N'Packaging standards and load security are acceptable', 11, 0, N'Quality', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (113, 11, N'Damaged, quarantined or non-conforming stock is controlled On Hold Products Red Card', 12, 0, N'Quality', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (114, 11, N'FIFO/stock rotation requirements are followed where applicable (New)', 13, 0, N'Quality', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (115, 11, N'Shift plan, priorities and cut-off times were communicated (Shift Start Up)', 14, 0, N'Performance', N'Per Shift', N'HOD', NULL, N'within the same shift'),
        (116, 11, N'Labour and equipment resources are adequate for the plan', 15, 0, N'Performance', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (117, 11, N'Shift KPIs, backlog and carry-over work were reviewed (RPS)', 16, 0, N'Performance', N'Per Shift', N'Senior Operator', N'HOD', N'by the next shift'),
        (118, 11, N'Team brief and safety message were completed ( Start of Each Shift Team Brief)', 17, 0, N'Morale', N'Per Shift', N'HOD', NULL, N'within the same shift'),
        (119, 11, N'Team concerns, support needs and training gaps were discussed', 18, 0, N'Morale', N'Per Shift', N'HOD', NULL, N'by the next shift'),
        (120, 11, N'Good performance and positive behaviours were recognised', 19, 0, N'Morale', N'Per Shift', N'Senior Operator', N'HOD', N'by the next shift'),
        (121, 11, N'General housekeeping and waste controls meet standard', 20, 0, N'H&S', N'Daily', N'Senior Operator', N'HOD', N'within the same day'),
        (122, 11, N'A sample of completed orders was checked for accuracy ( PickList V Shipping Documents)', 21, 0, N'Quality', N'Daily', N'Senior Operator', N'HOD', N'within the same day'),
        (123, 11, N'Daily output, service, productivity and missed deadlines were reviewed ( Transport Late Runners, No Shows)', 22, 0, N'Performance', N'Daily', N'Senior Operator', NULL, N'within the same day'),
        (124, 11, N'Absence, overtime, workload and welfare concerns were reviewed', 23, 0, N'Morale', N'Daily', N'HOD', NULL, N'within the same day'),
        (125, 12, N'Walkways, fire exits and emergency routes are clear', 0, 1, N'H&S', N'Hourly', N'Senior Operator', N'HOD', N'immediately'),
        (126, 12, N'PPE requirements are being followed', 1, 1, N'H&S', N'Hourly', N'Senior Operator', N'HOD', N'immediately'),
        (127, 12, N'No unsafe stacking, damaged pallets or falling-object risks (Mezz Floor)', 2, 1, N'H&S', N'Hourly', N'Senior Operator', NULL, N'immediately'),
        (128, 12, N'Loading bays, dock levellers and vehicle Security is safe (Rite Height)', 3, 1, N'H&S', N'Hourly', N'Senior Operator', N'HOD', N'immediately'),
        (129, 12, N'Correct product, quantity and destination are being picked (Bay Sheets)', 4, 1, N'Quality', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (130, 12, N'Labels, paperwork and scanning are accurate (Check Scanner V Loading)', 5, 1, N'Quality', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (131, 12, N'Picking and despatch activity is on plan', 6, 1, N'Performance', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (132, 12, N'Bottlenecks, downtime and waiting vehicles are controlled', 7, 1, N'Performance', N'Hourly', N'Senior Operator', NULL, N'within the same shift'),
        (133, 12, N'Pre-use equipment checks are completed and defects reported (Check Booklets)', 8, 0, N'H&S', N'Per Shift', N'Senior Operator', N'HOD', N'immediately'),
        (134, 12, N'Spill kits, first-aid and fire points are accessible', 9, 0, N'H&S', N'Per Shift', N'Senior Operator', NULL, N'immediately'),
        (135, 12, N'Pedestrian and MHE segregation controls are effective', 10, 0, N'H&S', N'Per Shift', N'Senior Operator', N'HOD', N'immediately'),
        (136, 12, N'Packaging standards and load security are acceptable', 11, 0, N'Quality', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (137, 12, N'Damaged, quarantined or non-conforming stock is controlled On Hold Products Red Card', 12, 0, N'Quality', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (138, 12, N'FIFO/stock rotation requirements are followed where applicable (New)', 13, 0, N'Quality', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (139, 12, N'Shift plan, priorities and cut-off times were communicated (Shift Start Up)', 14, 0, N'Performance', N'Per Shift', N'HOD', NULL, N'within the same shift'),
        (140, 12, N'Labour and equipment resources are adequate for the plan', 15, 0, N'Performance', N'Per Shift', N'Senior Operator', NULL, N'within the same shift'),
        (141, 12, N'Shift KPIs, backlog and carry-over work were reviewed (RPS)', 16, 0, N'Performance', N'Per Shift', N'Senior Operator', N'HOD', N'by the next shift'),
        (142, 12, N'Team brief and safety message were completed ( Start of Each Shift Team Brief)', 17, 0, N'Morale', N'Per Shift', N'HOD', NULL, N'within the same shift'),
        (143, 12, N'Team concerns, support needs and training gaps were discussed', 18, 0, N'Morale', N'Per Shift', N'HOD', NULL, N'by the next shift'),
        (144, 12, N'Good performance and positive behaviours were recognised', 19, 0, N'Morale', N'Per Shift', N'Senior Operator', N'HOD', N'by the next shift'),
        (145, 12, N'General housekeeping and waste controls meet standard', 20, 0, N'H&S', N'Daily', N'Senior Operator', N'HOD', N'within the same day'),
        (146, 12, N'A sample of completed orders was checked for accuracy ( PickList V Shipping Documents)', 21, 0, N'Quality', N'Daily', N'Senior Operator', N'HOD', N'within the same day'),
        (147, 12, N'Daily output, service, productivity and missed deadlines were reviewed ( Transport Late Runners, No Shows)', 22, 0, N'Performance', N'Daily', N'Senior Operator', NULL, N'within the same day'),
        (148, 12, N'Absence, overtime, workload and welfare concerns were reviewed', 23, 0, N'Morale', N'Daily', N'HOD', NULL, N'within the same day')
    ) AS s([Id], [TaskListId], [Text], [SortOrder], [IsTimeBoxed], [Category], [Cadence], [ResponsibleRole], [EscalateToRole], [EscalationWindow])
    ON t.[Id] = s.[Id]
    WHEN MATCHED THEN UPDATE SET t.[TaskListId] = s.[TaskListId], t.[Text] = s.[Text], t.[SortOrder] = s.[SortOrder], t.[IsTimeBoxed] = s.[IsTimeBoxed], t.[Category] = s.[Category], t.[Cadence] = s.[Cadence], t.[ResponsibleRole] = s.[ResponsibleRole], t.[EscalateToRole] = s.[EscalateToRole], t.[EscalationWindow] = s.[EscalationWindow]
    WHEN NOT MATCHED THEN INSERT ([Id], [TaskListId], [Text], [SortOrder], [IsTimeBoxed], [Category], [Cadence], [ResponsibleRole], [EscalateToRole], [EscalationWindow])
        VALUES (s.[Id], s.[TaskListId], s.[Text], s.[SortOrder], s.[IsTimeBoxed], s.[Category], s.[Cadence], s.[ResponsibleRole], s.[EscalateToRole], s.[EscalationWindow]);
    SET IDENTITY_INSERT [TaskItems] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908152553_SeedDispatchWarehouseAudit'
)
BEGIN
    SET IDENTITY_INSERT [TaskCheckpoints] ON;
    MERGE [TaskCheckpoints] AS t
    USING (VALUES
        (17, 53, N'Hour 1', 0),
        (18, 53, N'Hour 2', 1),
        (19, 53, N'Hour 3', 2),
        (20, 53, N'Hour 4', 3),
        (21, 53, N'Hour 5', 4),
        (22, 53, N'Hour 6', 5),
        (23, 53, N'Hour 7', 6),
        (24, 53, N'Hour 8', 7),
        (25, 54, N'Hour 1', 0),
        (26, 54, N'Hour 2', 1),
        (27, 54, N'Hour 3', 2),
        (28, 54, N'Hour 4', 3),
        (29, 54, N'Hour 5', 4),
        (30, 54, N'Hour 6', 5),
        (31, 54, N'Hour 7', 6),
        (32, 54, N'Hour 8', 7),
        (33, 55, N'Hour 1', 0),
        (34, 55, N'Hour 2', 1),
        (35, 55, N'Hour 3', 2),
        (36, 55, N'Hour 4', 3),
        (37, 55, N'Hour 5', 4),
        (38, 55, N'Hour 6', 5),
        (39, 55, N'Hour 7', 6),
        (40, 55, N'Hour 8', 7),
        (41, 56, N'Hour 1', 0),
        (42, 56, N'Hour 2', 1),
        (43, 56, N'Hour 3', 2),
        (44, 56, N'Hour 4', 3),
        (45, 56, N'Hour 5', 4),
        (46, 56, N'Hour 6', 5),
        (47, 56, N'Hour 7', 6),
        (48, 56, N'Hour 8', 7),
        (49, 57, N'Hour 1', 0),
        (50, 57, N'Hour 2', 1),
        (51, 57, N'Hour 3', 2),
        (52, 57, N'Hour 4', 3),
        (53, 57, N'Hour 5', 4),
        (54, 57, N'Hour 6', 5),
        (55, 57, N'Hour 7', 6),
        (56, 57, N'Hour 8', 7),
        (57, 58, N'Hour 1', 0),
        (58, 58, N'Hour 2', 1),
        (59, 58, N'Hour 3', 2),
        (60, 58, N'Hour 4', 3),
        (61, 58, N'Hour 5', 4),
        (62, 58, N'Hour 6', 5),
        (63, 58, N'Hour 7', 6),
        (64, 58, N'Hour 8', 7),
        (65, 59, N'Hour 1', 0),
        (66, 59, N'Hour 2', 1),
        (67, 59, N'Hour 3', 2),
        (68, 59, N'Hour 4', 3),
        (69, 59, N'Hour 5', 4),
        (70, 59, N'Hour 6', 5),
        (71, 59, N'Hour 7', 6),
        (72, 59, N'Hour 8', 7),
        (73, 60, N'Hour 1', 0),
        (74, 60, N'Hour 2', 1),
        (75, 60, N'Hour 3', 2),
        (76, 60, N'Hour 4', 3),
        (77, 60, N'Hour 5', 4),
        (78, 60, N'Hour 6', 5),
        (79, 60, N'Hour 7', 6),
        (80, 60, N'Hour 8', 7),
        (81, 77, N'Hour 1', 0),
        (82, 77, N'Hour 2', 1),
        (83, 77, N'Hour 3', 2),
        (84, 77, N'Hour 4', 3),
        (85, 77, N'Hour 5', 4),
        (86, 77, N'Hour 6', 5),
        (87, 77, N'Hour 7', 6),
        (88, 77, N'Hour 8', 7),
        (89, 78, N'Hour 1', 0),
        (90, 78, N'Hour 2', 1),
        (91, 78, N'Hour 3', 2),
        (92, 78, N'Hour 4', 3),
        (93, 78, N'Hour 5', 4),
        (94, 78, N'Hour 6', 5),
        (95, 78, N'Hour 7', 6),
        (96, 78, N'Hour 8', 7),
        (97, 79, N'Hour 1', 0),
        (98, 79, N'Hour 2', 1),
        (99, 79, N'Hour 3', 2),
        (100, 79, N'Hour 4', 3),
        (101, 79, N'Hour 5', 4),
        (102, 79, N'Hour 6', 5),
        (103, 79, N'Hour 7', 6),
        (104, 79, N'Hour 8', 7),
        (105, 80, N'Hour 1', 0),
        (106, 80, N'Hour 2', 1),
        (107, 80, N'Hour 3', 2),
        (108, 80, N'Hour 4', 3),
        (109, 80, N'Hour 5', 4),
        (110, 80, N'Hour 6', 5),
        (111, 80, N'Hour 7', 6),
        (112, 80, N'Hour 8', 7),
        (113, 81, N'Hour 1', 0),
        (114, 81, N'Hour 2', 1),
        (115, 81, N'Hour 3', 2),
        (116, 81, N'Hour 4', 3),
        (117, 81, N'Hour 5', 4),
        (118, 81, N'Hour 6', 5),
        (119, 81, N'Hour 7', 6),
        (120, 81, N'Hour 8', 7),
        (121, 82, N'Hour 1', 0),
        (122, 82, N'Hour 2', 1),
        (123, 82, N'Hour 3', 2),
        (124, 82, N'Hour 4', 3),
        (125, 82, N'Hour 5', 4),
        (126, 82, N'Hour 6', 5),
        (127, 82, N'Hour 7', 6),
        (128, 82, N'Hour 8', 7),
        (129, 83, N'Hour 1', 0),
        (130, 83, N'Hour 2', 1),
        (131, 83, N'Hour 3', 2),
        (132, 83, N'Hour 4', 3),
        (133, 83, N'Hour 5', 4),
        (134, 83, N'Hour 6', 5),
        (135, 83, N'Hour 7', 6),
        (136, 83, N'Hour 8', 7),
        (137, 84, N'Hour 1', 0),
        (138, 84, N'Hour 2', 1),
        (139, 84, N'Hour 3', 2),
        (140, 84, N'Hour 4', 3),
        (141, 84, N'Hour 5', 4),
        (142, 84, N'Hour 6', 5),
        (143, 84, N'Hour 7', 6),
        (144, 84, N'Hour 8', 7),
        (145, 101, N'Hour 1', 0),
        (146, 101, N'Hour 2', 1),
        (147, 101, N'Hour 3', 2),
        (148, 101, N'Hour 4', 3),
        (149, 101, N'Hour 5', 4),
        (150, 101, N'Hour 6', 5),
        (151, 101, N'Hour 7', 6),
        (152, 101, N'Hour 8', 7),
        (153, 102, N'Hour 1', 0),
        (154, 102, N'Hour 2', 1),
        (155, 102, N'Hour 3', 2),
        (156, 102, N'Hour 4', 3),
        (157, 102, N'Hour 5', 4),
        (158, 102, N'Hour 6', 5),
        (159, 102, N'Hour 7', 6),
        (160, 102, N'Hour 8', 7),
        (161, 103, N'Hour 1', 0),
        (162, 103, N'Hour 2', 1),
        (163, 103, N'Hour 3', 2),
        (164, 103, N'Hour 4', 3),
        (165, 103, N'Hour 5', 4),
        (166, 103, N'Hour 6', 5),
        (167, 103, N'Hour 7', 6),
        (168, 103, N'Hour 8', 7),
        (169, 104, N'Hour 1', 0),
        (170, 104, N'Hour 2', 1),
        (171, 104, N'Hour 3', 2),
        (172, 104, N'Hour 4', 3),
        (173, 104, N'Hour 5', 4),
        (174, 104, N'Hour 6', 5),
        (175, 104, N'Hour 7', 6),
        (176, 104, N'Hour 8', 7),
        (177, 105, N'Hour 1', 0),
        (178, 105, N'Hour 2', 1),
        (179, 105, N'Hour 3', 2),
        (180, 105, N'Hour 4', 3),
        (181, 105, N'Hour 5', 4),
        (182, 105, N'Hour 6', 5),
        (183, 105, N'Hour 7', 6),
        (184, 105, N'Hour 8', 7),
        (185, 106, N'Hour 1', 0),
        (186, 106, N'Hour 2', 1),
        (187, 106, N'Hour 3', 2),
        (188, 106, N'Hour 4', 3),
        (189, 106, N'Hour 5', 4),
        (190, 106, N'Hour 6', 5),
        (191, 106, N'Hour 7', 6),
        (192, 106, N'Hour 8', 7),
        (193, 107, N'Hour 1', 0),
        (194, 107, N'Hour 2', 1),
        (195, 107, N'Hour 3', 2),
        (196, 107, N'Hour 4', 3),
        (197, 107, N'Hour 5', 4),
        (198, 107, N'Hour 6', 5),
        (199, 107, N'Hour 7', 6),
        (200, 107, N'Hour 8', 7),
        (201, 108, N'Hour 1', 0),
        (202, 108, N'Hour 2', 1),
        (203, 108, N'Hour 3', 2),
        (204, 108, N'Hour 4', 3),
        (205, 108, N'Hour 5', 4),
        (206, 108, N'Hour 6', 5),
        (207, 108, N'Hour 7', 6),
        (208, 108, N'Hour 8', 7),
        (209, 125, N'Hour 1', 0),
        (210, 125, N'Hour 2', 1),
        (211, 125, N'Hour 3', 2),
        (212, 125, N'Hour 4', 3),
        (213, 125, N'Hour 5', 4),
        (214, 125, N'Hour 6', 5),
        (215, 125, N'Hour 7', 6),
        (216, 125, N'Hour 8', 7),
        (217, 126, N'Hour 1', 0),
        (218, 126, N'Hour 2', 1),
        (219, 126, N'Hour 3', 2),
        (220, 126, N'Hour 4', 3),
        (221, 126, N'Hour 5', 4),
        (222, 126, N'Hour 6', 5),
        (223, 126, N'Hour 7', 6),
        (224, 126, N'Hour 8', 7),
        (225, 127, N'Hour 1', 0),
        (226, 127, N'Hour 2', 1),
        (227, 127, N'Hour 3', 2),
        (228, 127, N'Hour 4', 3),
        (229, 127, N'Hour 5', 4),
        (230, 127, N'Hour 6', 5),
        (231, 127, N'Hour 7', 6),
        (232, 127, N'Hour 8', 7),
        (233, 128, N'Hour 1', 0),
        (234, 128, N'Hour 2', 1),
        (235, 128, N'Hour 3', 2),
        (236, 128, N'Hour 4', 3),
        (237, 128, N'Hour 5', 4),
        (238, 128, N'Hour 6', 5),
        (239, 128, N'Hour 7', 6),
        (240, 128, N'Hour 8', 7),
        (241, 129, N'Hour 1', 0),
        (242, 129, N'Hour 2', 1),
        (243, 129, N'Hour 3', 2),
        (244, 129, N'Hour 4', 3),
        (245, 129, N'Hour 5', 4),
        (246, 129, N'Hour 6', 5),
        (247, 129, N'Hour 7', 6),
        (248, 129, N'Hour 8', 7),
        (249, 130, N'Hour 1', 0),
        (250, 130, N'Hour 2', 1),
        (251, 130, N'Hour 3', 2),
        (252, 130, N'Hour 4', 3),
        (253, 130, N'Hour 5', 4),
        (254, 130, N'Hour 6', 5),
        (255, 130, N'Hour 7', 6),
        (256, 130, N'Hour 8', 7),
        (257, 131, N'Hour 1', 0),
        (258, 131, N'Hour 2', 1),
        (259, 131, N'Hour 3', 2),
        (260, 131, N'Hour 4', 3),
        (261, 131, N'Hour 5', 4),
        (262, 131, N'Hour 6', 5),
        (263, 131, N'Hour 7', 6),
        (264, 131, N'Hour 8', 7),
        (265, 132, N'Hour 1', 0),
        (266, 132, N'Hour 2', 1),
        (267, 132, N'Hour 3', 2),
        (268, 132, N'Hour 4', 3),
        (269, 132, N'Hour 5', 4),
        (270, 132, N'Hour 6', 5),
        (271, 132, N'Hour 7', 6),
        (272, 132, N'Hour 8', 7)
    ) AS s([Id], [TaskItemId], [Label], [SortOrder])
    ON t.[Id] = s.[Id]
    WHEN MATCHED THEN UPDATE SET t.[TaskItemId] = s.[TaskItemId], t.[Label] = s.[Label], t.[SortOrder] = s.[SortOrder]
    WHEN NOT MATCHED THEN INSERT ([Id], [TaskItemId], [Label], [SortOrder])
        VALUES (s.[Id], s.[TaskItemId], s.[Label], s.[SortOrder]);
    SET IDENTITY_INSERT [TaskCheckpoints] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908152553_SeedDispatchWarehouseAudit'
)
BEGIN
    SET IDENTITY_INSERT [RosterPeople] ON;
    MERGE [RosterPeople] AS t
    USING (VALUES
        (1, N'Hod', N'George Thompson', 1, 1),
        (2, N'Hod', N'Lukasz Jaworski', 2, 1),
        (3, N'Hod', N'Alison Gilley', 3, 1),
        (4, N'Hod', N'Piotr Pelka', 4, 1),
        (5, N'Hod', N'Michael Tregillis', 5, 1)
    ) AS s([Id], [ListKind], [Name], [SortOrder], [IsActive])
    ON t.[Id] = s.[Id]
    WHEN MATCHED THEN UPDATE SET t.[ListKind] = s.[ListKind], t.[Name] = s.[Name], t.[SortOrder] = s.[SortOrder], t.[IsActive] = s.[IsActive]
    WHEN NOT MATCHED THEN INSERT ([Id], [ListKind], [Name], [SortOrder], [IsActive])
        VALUES (s.[Id], s.[ListKind], s.[Name], s.[SortOrder], s.[IsActive]);
    SET IDENTITY_INSERT [RosterPeople] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908152553_SeedDispatchWarehouseAudit'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260908152553_SeedDispatchWarehouseAudit', N'8.0.0');
END;
GO

COMMIT;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908153012_AddCheckpointStatus'
)
BEGIN
    ALTER TABLE [CheckpointResponses] ADD [Status] nvarchar(20) NULL;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260908153012_AddCheckpointStatus'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260908153012_AddCheckpointStatus', N'8.0.0');
END;
GO

COMMIT;
GO

