/* =====================================================================
   Support Audit System — full database provisioning script
   Target: SQL Server (CSMSVR02), database RittalSupportSW

   Run once against the SQL Server instance (SSMS or sqlcmd). It is
   idempotent — safe to re-run; existing objects and seeded rows are left
   alone. It creates:
     1. the RittalSupportSW database (if missing),
     2. the db_Public_User login/user the app connects as,
     3. the full schema (tables, keys, indexes),
     4. the Stores + Dispatch seed data (verbatim task lists, SHEF014),
     5. the EF migration-history rows, so the app's startup migration
        sees everything as already applied and makes no further changes.

   sqlcmd:  sqlcmd -S csmsvr02 -E -i create-database.sql
   (Change the login password below before running in production.)
   ===================================================================== */

IF DB_ID(N'RittalSupportSW') IS NULL
BEGIN
    CREATE DATABASE [RittalSupportSW];
END;
GO

USE [RittalSupportSW];
GO

/* ---- Application SQL login / user -----------------------------------
   Matches ConnectionStrings:Default in appsettings.json. Rotate this
   password in production and keep the connection string in step.
   Uses db_owner so the app can also apply future EF migrations on start. */
IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'db_Public_User')
BEGIN
    CREATE LOGIN [db_Public_User] WITH PASSWORD = N'Rittal1234',
        CHECK_POLICY = OFF, DEFAULT_DATABASE = [RittalSupportSW];
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'db_Public_User')
BEGIN
    CREATE USER [db_Public_User] FOR LOGIN [db_Public_User];
    ALTER ROLE [db_owner] ADD MEMBER [db_Public_User];
END;
GO

/* ---- Schema + seed data + migration history -------------------------
   (generated by: dotnet ef migrations script --idempotent) */

IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [Departments] (
        [Id] int NOT NULL IDENTITY,
        [Name] nvarchar(200) NOT NULL,
        [SortOrder] int NOT NULL,
        [IsActive] bit NOT NULL,
        CONSTRAINT [PK_Departments] PRIMARY KEY ([Id])
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [Areas] (
        [Id] int NOT NULL IDENTITY,
        [DepartmentId] int NOT NULL,
        [Name] nvarchar(200) NOT NULL,
        [DefaultLocation] nvarchar(max) NULL,
        [SortOrder] int NOT NULL,
        [IsActive] bit NOT NULL,
        CONSTRAINT [PK_Areas] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_Areas_Departments_DepartmentId] FOREIGN KEY ([DepartmentId]) REFERENCES [Departments] ([Id]) ON DELETE CASCADE
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [Shifts] (
        [Id] int NOT NULL IDENTITY,
        [DepartmentId] int NOT NULL,
        [Name] nvarchar(200) NOT NULL,
        [SortOrder] int NOT NULL,
        [IsActive] bit NOT NULL,
        CONSTRAINT [PK_Shifts] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_Shifts_Departments_DepartmentId] FOREIGN KEY ([DepartmentId]) REFERENCES [Departments] ([Id]) ON DELETE CASCADE
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [TaskLists] (
        [Id] int NOT NULL IDENTITY,
        [AreaId] int NOT NULL,
        [ShiftId] int NOT NULL,
        [Version] int NOT NULL,
        [IsCurrent] bit NOT NULL,
        [HealthRepsReminder] nvarchar(max) NULL,
        [CreatedAt] datetime2 NOT NULL,
        [CreatedBy] nvarchar(256) NULL,
        CONSTRAINT [PK_TaskLists] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_TaskLists_Areas_AreaId] FOREIGN KEY ([AreaId]) REFERENCES [Areas] ([Id]) ON DELETE CASCADE,
        CONSTRAINT [FK_TaskLists_Shifts_ShiftId] FOREIGN KEY ([ShiftId]) REFERENCES [Shifts] ([Id]) ON DELETE NO ACTION
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [ChecklistSubmissions] (
        [Id] int NOT NULL IDENTITY,
        [AreaId] int NOT NULL,
        [ShiftId] int NOT NULL,
        [TaskListId] int NOT NULL,
        [ChecklistDate] date NOT NULL,
        [AuditorNames] nvarchar(max) NULL,
        [Location] nvarchar(max) NULL,
        [CreatedAt] datetime2 NOT NULL,
        [CreatedBy] nvarchar(256) NULL,
        [LastEditedAt] datetime2 NULL,
        [LastEditedBy] nvarchar(256) NULL,
        [CompletedAt] datetime2 NULL,
        [CompletedBy] nvarchar(256) NULL,
        CONSTRAINT [PK_ChecklistSubmissions] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_ChecklistSubmissions_Areas_AreaId] FOREIGN KEY ([AreaId]) REFERENCES [Areas] ([Id]) ON DELETE NO ACTION,
        CONSTRAINT [FK_ChecklistSubmissions_Shifts_ShiftId] FOREIGN KEY ([ShiftId]) REFERENCES [Shifts] ([Id]) ON DELETE NO ACTION,
        CONSTRAINT [FK_ChecklistSubmissions_TaskLists_TaskListId] FOREIGN KEY ([TaskListId]) REFERENCES [TaskLists] ([Id]) ON DELETE NO ACTION
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [TaskItems] (
        [Id] int NOT NULL IDENTITY,
        [TaskListId] int NOT NULL,
        [Text] nvarchar(max) NOT NULL,
        [SortOrder] int NOT NULL,
        [IsTimeBoxed] bit NOT NULL,
        CONSTRAINT [PK_TaskItems] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_TaskItems_TaskLists_TaskListId] FOREIGN KEY ([TaskListId]) REFERENCES [TaskLists] ([Id]) ON DELETE CASCADE
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [TaskCheckpoints] (
        [Id] int NOT NULL IDENTITY,
        [TaskItemId] int NOT NULL,
        [Label] nvarchar(120) NOT NULL,
        [SortOrder] int NOT NULL,
        CONSTRAINT [PK_TaskCheckpoints] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_TaskCheckpoints_TaskItems_TaskItemId] FOREIGN KEY ([TaskItemId]) REFERENCES [TaskItems] ([Id]) ON DELETE CASCADE
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [TaskResponses] (
        [Id] int NOT NULL IDENTITY,
        [ChecklistSubmissionId] int NOT NULL,
        [TaskItemId] int NOT NULL,
        [Status] nvarchar(20) NULL,
        [Notes] nvarchar(max) NULL,
        [UpdatedAt] datetime2 NULL,
        CONSTRAINT [PK_TaskResponses] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_TaskResponses_ChecklistSubmissions_ChecklistSubmissionId] FOREIGN KEY ([ChecklistSubmissionId]) REFERENCES [ChecklistSubmissions] ([Id]) ON DELETE CASCADE,
        CONSTRAINT [FK_TaskResponses_TaskItems_TaskItemId] FOREIGN KEY ([TaskItemId]) REFERENCES [TaskItems] ([Id]) ON DELETE NO ACTION
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE TABLE [CheckpointResponses] (
        [Id] int NOT NULL IDENTITY,
        [TaskResponseId] int NOT NULL,
        [TaskCheckpointId] int NOT NULL,
        [Ticked] bit NOT NULL,
        [TickedAt] datetime2 NULL,
        CONSTRAINT [PK_CheckpointResponses] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_CheckpointResponses_TaskCheckpoints_TaskCheckpointId] FOREIGN KEY ([TaskCheckpointId]) REFERENCES [TaskCheckpoints] ([Id]) ON DELETE NO ACTION,
        CONSTRAINT [FK_CheckpointResponses_TaskResponses_TaskResponseId] FOREIGN KEY ([TaskResponseId]) REFERENCES [TaskResponses] ([Id]) ON DELETE CASCADE
    );
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE UNIQUE INDEX [IX_Areas_DepartmentId_Name] ON [Areas] ([DepartmentId], [Name]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_ChecklistSubmissions_AreaId] ON [ChecklistSubmissions] ([AreaId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_ChecklistSubmissions_ChecklistDate_AreaId_ShiftId] ON [ChecklistSubmissions] ([ChecklistDate], [AreaId], [ShiftId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_ChecklistSubmissions_ShiftId] ON [ChecklistSubmissions] ([ShiftId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_ChecklistSubmissions_TaskListId] ON [ChecklistSubmissions] ([TaskListId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_CheckpointResponses_TaskCheckpointId] ON [CheckpointResponses] ([TaskCheckpointId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_CheckpointResponses_TaskResponseId] ON [CheckpointResponses] ([TaskResponseId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE UNIQUE INDEX [IX_Departments_Name] ON [Departments] ([Name]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE UNIQUE INDEX [IX_Shifts_DepartmentId_Name] ON [Shifts] ([DepartmentId], [Name]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_TaskCheckpoints_TaskItemId] ON [TaskCheckpoints] ([TaskItemId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_TaskItems_TaskListId] ON [TaskItems] ([TaskListId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_TaskLists_AreaId_ShiftId_IsCurrent] ON [TaskLists] ([AreaId], [ShiftId], [IsCurrent]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_TaskLists_ShiftId] ON [TaskLists] ([ShiftId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_TaskResponses_ChecklistSubmissionId_TaskItemId] ON [TaskResponses] ([ChecklistSubmissionId], [TaskItemId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_TaskResponses_TaskItemId] ON [TaskResponses] ([TaskItemId]);
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093357_InitialCreate'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260907093357_InitialCreate', N'8.0.0');
END;
GO

COMMIT;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093744_SeedSupportData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Name', N'SortOrder', N'IsActive') AND [object_id] = OBJECT_ID(N'[Departments]'))
        SET IDENTITY_INSERT [Departments] ON;
    EXEC(N'INSERT INTO [Departments] ([Id], [Name], [SortOrder], [IsActive])
    VALUES (1, N''Stores'', 1, CAST(1 AS bit)),
    (2, N''Dispatch'', 2, CAST(1 AS bit))');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Name', N'SortOrder', N'IsActive') AND [object_id] = OBJECT_ID(N'[Departments]'))
        SET IDENTITY_INSERT [Departments] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093744_SeedSupportData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'DepartmentId', N'Name', N'DefaultLocation', N'SortOrder', N'IsActive') AND [object_id] = OBJECT_ID(N'[Areas]'))
        SET IDENTITY_INSERT [Areas] ON;
    EXEC(N'INSERT INTO [Areas] ([Id], [DepartmentId], [Name], [DefaultLocation], [SortOrder], [IsActive])
    VALUES (1, 1, N''Stores DP1 & DP3'', N''DP1 & DP3'', 1, CAST(1 AS bit)),
    (2, 1, N''Consumables'', N''Consumables'', 2, CAST(1 AS bit))');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'DepartmentId', N'Name', N'DefaultLocation', N'SortOrder', N'IsActive') AND [object_id] = OBJECT_ID(N'[Areas]'))
        SET IDENTITY_INSERT [Areas] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093744_SeedSupportData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'DepartmentId', N'Name', N'SortOrder', N'IsActive') AND [object_id] = OBJECT_ID(N'[Shifts]'))
        SET IDENTITY_INSERT [Shifts] ON;
    EXEC(N'INSERT INTO [Shifts] ([Id], [DepartmentId], [Name], [SortOrder], [IsActive])
    VALUES (1, 1, N''1st'', 1, CAST(1 AS bit)),
    (2, 1, N''2nd'', 2, CAST(1 AS bit)),
    (3, 1, N''3rd'', 3, CAST(1 AS bit)),
    (4, 1, N''Continental nights'', 4, CAST(1 AS bit))');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'DepartmentId', N'Name', N'SortOrder', N'IsActive') AND [object_id] = OBJECT_ID(N'[Shifts]'))
        SET IDENTITY_INSERT [Shifts] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093744_SeedSupportData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'AreaId', N'ShiftId', N'Version', N'IsCurrent', N'HealthRepsReminder', N'CreatedAt', N'CreatedBy') AND [object_id] = OBJECT_ID(N'[TaskLists]'))
        SET IDENTITY_INSERT [TaskLists] ON;
    EXEC(N'INSERT INTO [TaskLists] ([Id], [AreaId], [ShiftId], [Version], [IsCurrent], [HealthRepsReminder], [CreatedAt], [CreatedBy])
    VALUES (1, 1, 1, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed''),
    (2, 1, 2, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed''),
    (3, 1, 3, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed''),
    (4, 1, 4, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed''),
    (5, 2, 1, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed''),
    (6, 2, 2, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed''),
    (7, 2, 3, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed''),
    (8, 2, 4, 1, CAST(1 AS bit), N''Please remember to check on the health and wellbeing of your team throughout the shift, and make sure you know who your Health & Safety Representatives are.'', ''2026-01-01T00:00:00.0000000Z'', N''System seed'')');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'AreaId', N'ShiftId', N'Version', N'IsCurrent', N'HealthRepsReminder', N'CreatedAt', N'CreatedBy') AND [object_id] = OBJECT_ID(N'[TaskLists]'))
        SET IDENTITY_INSERT [TaskLists] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093744_SeedSupportData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'TaskListId', N'Text', N'SortOrder', N'IsTimeBoxed') AND [object_id] = OBJECT_ID(N'[TaskItems]'))
        SET IDENTITY_INSERT [TaskItems] ON;
    EXEC(N'INSERT INTO [TaskItems] ([Id], [TaskListId], [Text], [SortOrder], [IsTimeBoxed])
    VALUES (1, 1, N''Complete pre shift check book been done on the forklift/ ppt and pallet trucks'', 0, CAST(0 AS bit)),
    (2, 1, N''Tidy the yard at both ends and ensure returns ready for collection: pallets / stillages & German returns'', 1, CAST(0 AS bit)),
    (3, 1, N''order everything for today’s production (spc / AMC TRACKING sheet)'', 2, CAST(0 AS bit)),
    (4, 1, N''stock check the gas at dp1 and raise any shortages. correct if needed on sap'', 3, CAST(0 AS bit)),
    (5, 1, N''Check that the gas cage is tidy and all bottles stored safely, action if not'', 4, CAST(0 AS bit)),
    (6, 1, N''Count pallet trailers and raise potential shortages for the next shift - Escalate any issues.'', 5, CAST(0 AS bit)),
    (7, 1, N''send any parcels to consumables to be processed – first batch by 9.30am'', 6, CAST(0 AS bit)),
    (8, 1, N''send any parcels to consumables to be processed – Batch 2 by 11.30am'', 7, CAST(0 AS bit)),
    (9, 1, N''send any parcels to consumables to be processed – batch 3 by 1.30pm'', 8, CAST(0 AS bit)),
    (10, 1, N''Inspect racking areas and report any damage, also remove any unnecessary banding or shrink wrap you find hanging from the racks'', 9, CAST(0 AS bit)),
    (11, 1, N''inspect floors and fire exit and ensure they are clear of obstructions. IE: Pallets, stillages and empty crates'', 10, CAST(1 AS bit)),
    (12, 1, N''Check verticals on order to replace any pallets used'', 11, CAST(1 AS bit)),
    (13, 1, N''Inspect DP1 – move any pallets of steel over hanging the WALKWAYS and ensure coils are not exceeding the blue height restriction line'', 12, CAST(0 AS bit)),
    (14, 1, N''inspect pallets in stores and ensure we have no sharp edge pallets'', 13, CAST(0 AS bit)),
    (15, 1, N''sweep through the store and ensure it is tidy for the next shift.'', 14, CAST(0 AS bit)),
    (16, 2, N''has the pre shift check books been done on the forklift / ppt and the pallets trucks?'', 0, CAST(0 AS bit)),
    (17, 2, N''Have the pallet trailers been counted and any potential shortages been raised for the next shift? Escalate any issues.'', 1, CAST(0 AS bit)),
    (18, 2, N''Have we ordered the tx so it’s on site for 23:00 start'', 2, CAST(0 AS bit)),
    (19, 2, N''Have we located everything that was booked in by the previous shift and cleared option 1 put away?'', 3, CAST(0 AS bit)),
    (20, 2, N''is the mla area clean and tidy with no returned stock just sitting around. If SO, please return to the correct stores'', 4, CAST(0 AS bit)),
    (21, 2, N''Check the racking for anything hanging down and correct this IE: banding, shrink wrap etc.'', 5, CAST(0 AS bit)),
    (22, 2, N''Has the parcel shelf been sent to consumables to be processed? Every 2 hours'', 6, CAST(1 AS bit)),
    (23, 2, N''Are racking areas safe? And all damage if any has been reported'', 7, CAST(0 AS bit)),
    (24, 2, N''Are floors and fire exit clear of obstructions. IE: Pallets, stillages and empty crates'', 8, CAST(0 AS bit)),
    (25, 2, N''have the scrap caps been loaded onto the Ferguson’s trailer'', 9, CAST(0 AS bit)),
    (26, 2, N''Have we cycle counted the pallet trailers and corrected the stocks'', 10, CAST(0 AS bit)),
    (27, 2, N''have the verticals been ordered every time we issue a pallet so we have constant stock flow?'', 11, CAST(0 AS bit)),
    (28, 2, N''Are pallets of steel over hanging the WALKWAYS in dp1 and not exceeding the blue hight restriction line?'', 12, CAST(0 AS bit)),
    (29, 2, N''are the operators ENSURING that we have no sharp edge pallets in the stores'', 13, CAST(0 AS bit)),
    (30, 2, N''have we swept through the store and is it tidy for the next shift.'', 14, CAST(0 AS bit)),
    (31, 3, N''Has the pre shift check book been done on the forklift/ ppt and pallet trucks?'', 0, CAST(0 AS bit)),
    (32, 3, N''Are racking areas safe? And all damage if any has been reported'', 1, CAST(0 AS bit)),
    (33, 3, N''Are all pallets strapped and stored safely at DP1 / DP3'', 2, CAST(0 AS bit)),
    (34, 3, N''Is the TX on the line and not still in stores?'', 3, CAST(0 AS bit)),
    (35, 3, N''Have the parcels been sent to consumables to be processed? Every two hours on this!'', 4, CAST(1 AS bit)),
    (36, 3, N''Are floors and fire exit clear of obstructions. IE: Pallets, stillages and empty crates'', 5, CAST(0 AS bit)),
    (37, 3, N''Do the racks have any banding or shrink wrap hanging from them that needs removing?'', 6, CAST(0 AS bit)),
    (38, 3, N''Are pallets of steel over hanging the WALKWAYS in dp1 and not exceeding the blue hight restriction line?'', 7, CAST(0 AS bit)),
    (39, 3, N''Are the cycle counts done for the day and if not please ensure they are finished.'', 8, CAST(0 AS bit)),
    (40, 3, N''are the operators ENSURING that we have no sharp edge pallets in the stores'', 9, CAST(0 AS bit)),
    (41, 3, N''Is the put away clear for the next shift and all deliveries put away?'', 10, CAST(0 AS bit)),
    (42, 3, N''have we swept through the store and is it tidy for the next shift.'', 11, CAST(0 AS bit));
    INSERT INTO [TaskItems] ([Id], [TaskListId], [Text], [SortOrder], [IsTimeBoxed])
    VALUES (43, 4, N''Has the pre shift check book been done on the forklift/ ppt and pallet trucks?'', 0, CAST(0 AS bit)),
    (44, 4, N''Are racking areas safe? And all damage if any has been reported'', 1, CAST(0 AS bit)),
    (45, 4, N''Are all pallets strapped and stored safely at DP1'', 2, CAST(0 AS bit)),
    (46, 4, N''Is the coils area safe and nothing blocking the fire exit or obstructing the WALKWAYS'', 3, CAST(0 AS bit)),
    (47, 4, N''Do the racks have any banding or shrink wrap hanging from them that needs removing?'', 4, CAST(0 AS bit)),
    (48, 4, N''Are pallets of steel over hanging the WALKWAYS in dp1 and not exceeding the blue hight restriction line?'', 5, CAST(0 AS bit)),
    (49, 4, N''Are the cycle counts done for the day and if not please ensure they are finished.'', 6, CAST(0 AS bit)),
    (50, 4, N''Is the put away clear for the next shift and all deliveries put away?'', 7, CAST(0 AS bit)),
    (51, 4, N''Have the scrap tables and bins been emptied for the next shift and not left so production is stopped at 07:00'', 8, CAST(0 AS bit)),
    (52, 4, N''have we swept through the store and is it tidy for the next shift. If no ask DP3 to support'', 9, CAST(0 AS bit))');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'TaskListId', N'Text', N'SortOrder', N'IsTimeBoxed') AND [object_id] = OBJECT_ID(N'[TaskItems]'))
        SET IDENTITY_INSERT [TaskItems] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093744_SeedSupportData'
)
BEGIN
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'TaskItemId', N'Label', N'SortOrder') AND [object_id] = OBJECT_ID(N'[TaskCheckpoints]'))
        SET IDENTITY_INSERT [TaskCheckpoints] ON;
    EXEC(N'INSERT INTO [TaskCheckpoints] ([Id], [TaskItemId], [Label], [SortOrder])
    VALUES (1, 11, N''9am'', 0),
    (2, 11, N''11am'', 1),
    (3, 11, N''1pm'', 2),
    (4, 11, N''3pm'', 3),
    (5, 12, N''9am'', 0),
    (6, 12, N''11am'', 1),
    (7, 12, N''1pm'', 2),
    (8, 12, N''3pm'', 3),
    (9, 22, N''Batch 1'', 0),
    (10, 22, N''Batch 2'', 1),
    (11, 22, N''Batch 3'', 2),
    (12, 22, N''Batch 4'', 3),
    (13, 35, N''Batch 1'', 0),
    (14, 35, N''Batch 2'', 1),
    (15, 35, N''Batch 3'', 2),
    (16, 35, N''Batch 4'', 3)');
    IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'TaskItemId', N'Label', N'SortOrder') AND [object_id] = OBJECT_ID(N'[TaskCheckpoints]'))
        SET IDENTITY_INSERT [TaskCheckpoints] OFF;
END;
GO

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260907093744_SeedSupportData'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260907093744_SeedSupportData', N'8.0.0');
END;
GO

COMMIT;
GO

